FROM python:3.12.7-slim

RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.releasetools.txt .
RUN python3 -m pip install --no-cache-dir -r requirements.releasetools.txt
RUN rm requirements.releasetools.txt
