name: Test build docker

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Docker image with pyziomki's dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: Dockerfile.doctools
          tags: ${{ steps.meta.outputs.tags }}
