name: Test build docker

on:
  pull_request:
    branches: [ main ]

jobs:
  automerge:
    uses: fizyk/actions-reuse/.github/workflows/automerge-shared.yml@v1.7.1
    secrets:
      app_id: ${{ secrets.MERGE_APP_ID }}
      private_key: ${{ secrets.MERGE_APP_PRIVATE_KEY }}
