name: Test build docker

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Docker image with pyziomki's dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - name: Build doctools docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          file: Dockerfile.doctools

      - name: Build Releasetools docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          file: Dockerfile.releasetools
