# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  push:
    tags:
      - v*

jobs:
  push_doctools_to_registry:
    name: Push Doctools Docker image to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: clearcode/pyziomkidoctools
          flavor: |
            latest=true
          tags: |
            type=pep440,pattern={{version}}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push doctools docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile.doctools
          tags: ${{ steps.meta.outputs.tags }}

  push_releasetools_to_registry:
    name: Push Releasetools Docker image to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.5

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: clearcode/pyziomkireleasetools
          flavor: |
            latest=true
          tags: |
            type=pep440,pattern={{version}}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push releasetools docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile.releasetools
          tags: ${{ steps.meta.outputs.tags }}
