# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_doctools_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docktools docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: Dockerfile.doctools
          tags: clearcode/pyziomkidoctools:latest

      - name: Build and push Releasetools docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: Dockerfile.releasetools
          tags: clearcode/pyziomkireleasetools:latest
